### ISSUE TITLE
Compatibility PhpStorm 2019.1

### ISSUE THREAD

**Issue by marcorieser** [Alicannklc/intellij-tailwind-css#1]
Please make the plugin combatible with PhpStorm 2019.1.

**Comment by Alicannklc** [comment]
Uptading versions thanks you 

https://plugins.jetbrains.com/plugin/12074-tailwindcss/update/60543

**Comment by Alicannklc** [comment]
1.0.2
Phpstrom 2019.1
![1.0.2](https://i.resimyukle.xyz/S6JIcL.png)
