### ISSUE TITLE
Support for @tailwind import statement

### ISSUE THREAD

**Issue by GMartigny** [Alicannklc/intellij-tailwind-css#10]
Hi 👋,

When I import Tailwind using the `@tailwind` statement [according to the documentation](https://tailwindcss.com/docs/installation#2-add-tailwind-to-your-css), I got an error `"Unknown CSS at-rule"`. Is there a chance to support that statement with this plugin ?

```css
@tailwind base; /* Highlited as incorrect */

body {
  @apply .bg-gray-500; /* No issue */
}
```

Thanks

**Comment by Alicannklc** [comment]
Unfortunately, purely because of the ide

**Comment by GMartigny** [comment]
Ok too bad. Thanks for quick answer and the useful plugin ! 👍

**Comment by Alicannklc** [comment]
![b2b3501ef9bb9f667616ad0893d018c1](https://user-images.githubusercontent.com/34812598/71045325-99803e00-2145-11ea-8853-c3732932d7d2.jpg)

**Comment by GMartigny** [comment]
Hi, I fix the issue by changing the way the IDE looks at the file.
In Settings -> Languages & Frameworks -> Style Sheets -> Dialects, I change the dialect to PostCSS.
Before 
![image](https://user-images.githubusercontent.com/2543511/71129231-4a8ee300-21ef-11ea-9ea0-e0968330c3db.png)

After
![image](https://user-images.githubusercontent.com/2543511/71129257-58446880-21ef-11ea-9298-46244fdb9071.png)
