### ISSUE TITLE
Tailwind 1.0+

### ISSUE THREAD

**Issue by coryrose1** [Alicannklc/intellij-tailwind-css#2]
Hi,

Thanks for creating this plugin!

Can this plugin be updated to reflect Tailwind 1.0 as many class names have changed?

Thanks again!

**Comment by analytically** [comment]
+1

**Comment by analytically** [comment]
@Alicannklc

**Comment by Alicannklc** [comment]
add 1.0.0 https://github.com/Alicannklc/intellij-tailwind-css/blob/master/src/main/resources/liveTemplates/Tailwindcss-1_0_0.xml
