### ISSUE TITLE
IntelliSense doubled

### ISSUE THREAD

**Issue by Lothindir** [Alicannklc/intellij-tailwind-css#3]
Hello, while using your plugin all the IntelliSense is doubled. I checked and I don't have any other plugin that gives me TailwindCSS IntelliSense.
![tailwindcss-jb-plugin](https://user-images.githubusercontent.com/14940642/59350670-f3c6bf00-8d1c-11e9-89f2-862239bbf01e.png)

I have the version 1.0.4.

Ty for you work.

**Comment by eFlowMedia** [comment]
Hello.  I am having the same issue.  Version 1.0.4 . Thanks

**Comment by Alicannklc** [comment]
Thanks fixing update 

![image](https://user-images.githubusercontent.com/34812598/59493054-0531d780-8e93-11e9-87c0-eb07979633d7.png)
