### ISSUE TITLE
Feature: React className support

### ISSUE THREAD

**Issue by JasonTheAdams** [Alicannklc/intellij-tailwind-css#6]
It would be great to have support for React, specifically the `className` prop:
```jsx
<Control className="p-1 text-gray-700" />
```

**Comment by Alicannklc** [comment]
Unfortunately, I can't give this support.

**Comment by wanjas** [comment]
A little workaround to have hints for className:
You can open project's tree and mark node_modules/tailwindcss/dist as "not excluded" ("Mark Directory As" option in the menu). This will give you all the standard class names.

**Comment by Alicannklc** [comment]
![image](https://user-images.githubusercontent.com/34812598/61675036-42458100-acff-11e9-9f5c-9b7c9dd0922c.png)
Update classname support
