### ISSUE TITLE
Custom tailwind classes

### ISSUE THREAD

**Issue by manniL** [Alicannklc/intellij-tailwind-css#9]
Hey 👋 

Is it possible to have intellisense for custom classes (or custom values in your tailwind config)?

**Comment by Alicannklc** [comment]
Only automatic filling is available

**Comment by manniL** [comment]
So it only supports the "default" tailwind classes? ☺️

**Comment by Alicannklc** [comment]
yes default classes [https://www.jetbrains.com/help/idea/using-live-templates.html](live template)
